#config for mail server
mail:
    mail_host: smtp.gmail.com
    mail_port: 465
    mail_user: 
    mail_passwd: 
    log_file: ../tools/log/mail.log


#proxy server config
proxy:
    use_proxy: yes
    proxy_host: 
    proxy_port: 10808
    proxy_user: 
    proxy_passwd: 
    #proxy_type just support socks5 socks4 http
    proxy_type: socks5

#set es config
es:
    es_host: 127.0.0.1
    es_port: 9200
    es_user:
    es_passwd:


#set mysql config
mysql:
    db_host: 127.0.0.1
    db_user:
    db_passwd:
    db_name:
    db_port: 3306
    
